### PR TITLE
fix: the connection must be closed in other states

### PR DESCRIPTION
**Pull request by vtihobrazov-ms**

### CODE REVIEW

**Comment by britzl** [comment]
Thank you! Could you please tell me under which circumstances this becomes a problem?

**Comment by vtihobrazov-ms** [comment]
For example, when the connection is closed on the handshake. In this case, it does not close.

**Comment by vtihobrazov-ms** [comment]
There are many different situations where the connection can be closed before setting the state STATE_CONNECTED

**Comment by britzl** [comment]
> For example, when the connection is closed on the handshake. In this case, it does not close

Ah, yes, makes sense! Thanks.

**Pull request merged**
